[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
live_config_reload = true
import = ["/home/bochkare/.config/alacritty/base16-gruvbox-dark-medium-256.toml"]

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[window]
decorations = "none"
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 5

[colors]
draw_bold_text_with_bright_colors = false

[keyboard]
