#!/bin/bash

PROTOCOL="$1"
TEMPLATE="$2"
QUTE_URL=$(echo "$QUTE_URL" | tr -d '\n' | jq -sRr @uri )

OUT="org-protocol://$PROTOCOL?template=$TEMPLATE&url=$QUTE_URL&title=$QUTE_TITLE&body=$QUTE_SELECTED_TEXT"

echo "Out is: $OUT"
xdg-open "$OUT"
