# See also the official docs: https://beets.readthedocs.io/en/stable/reference/config.html

directory: ~/Music
library: ~/Music/beets-library.db

paths:
  singleton: Non-Album/%the{$artist}/$title
  comp: Compilations/$album%aunique{}/$track $title
  albumtype:soundtrack: Soundtracks/$album/$track $title
  default: %the{$albumartist}/$album%aunique{}/$track $title

import:
  move: yes
  log: ~/Music/beets-import.log

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: magenta
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

######################################################################
## Plugins setup

plugins: convert edit fetchart lastgenre lyrics mpdstats mpdupdate the fuzzy info ydl chroma

convert:
  auto: true
  delete_originals: true

# Fetch album art
# pip install requests

fetchart:
  auto: yes
  maxwidth: 800

# Fetch genres info
# pip install pylast
lastgenre:
  auto: yes

# Fetch lyrics
lyrics:
  auto: yes

chroma:
  auto: no
